---
apiVersion: v1
kind: Namespace
metadata:
  name: codeserver

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-cm
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-cm
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-188.166.199.53.nip.io

---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-secret
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-pvc
spec:
  storageClassName: do-block-storage
  # storageClassName: do-block-storage-retain # retain the volume after pod deleted
  accessModes:
    - ReadWriteOnce # can be only mounted by a single node
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-deploy
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
      name: codeserver-po
  template:
    metadata:
      name: codeserver-po
      labels:
        app: codeserver
        name: codeserver-po
    spec:
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: codeserver-pvc
        - name: cm-vol
          configMap:
            name: codeserver-cm
        - name: secret-vol
          secret:
            secretName: codeserver-secret
      containers:
      - name: codeserver-container
        image: linuxserver/code-server:latest
        imagePullPolicy: IfNotPresent
        envFrom: # to set the environment variables from configmap and secret
          - configMapRef:
              name: codeserver-cm
          - secretRef:
              name: codeserver-secret
        ports:
        - containerPort: 8443
        volumeMounts:
          - name: data-vol
            mountPath: /config/workspace
          - name: cm-vol
            mountPath: /opt/configmap
          - name: secret-vol
            mountPath: /opt/secret
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 100m
            memory: 500Mi
---

apiVersion: v1
kind: Service
metadata:
  name: codeserver-svc
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-svc
spec:
  type: ClusterIP
  selector:
    app: codeserver
    name: codeserver-po
  ports:
  - port: 8080
    targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeserver-ing
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-ing
spec:
  ingressClassName: nginx
  rules:
  - host: code-188.166.199.53.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: codeserver-svc
            port:
              number: 8080