apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels: #to select the correct pod(s) to manage
      app: bgg
      name: bggapp-po
  template:
    # the pod template
    metadata:
      name: bggapp-po
      labels:
        app: bgg
        name: bggapp-po
    spec:
      containers:
        - name: app-container
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bgg-cm
            - secretRef:
                name: bgg-secret
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-svc
spec:
  type: ClusterIP # service only available in cluster 
  # type: NodePort # to expose the service to the outside of cluster
  # type: LoadBalancer
  selector:
    app: bgg
    name: bggapp-po
  ports:
    - name: dov-svc-port
      protocol: TCP
      port: 80 # service port
      targetPort: 3000 # container port